/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_hacks_ndkdemo_MyActivity */

#ifndef _Included_com_example_enability_visionsimulator_diabeticretinopathysim
#define _Included_com_example_enability_visionsimulator_diabeticretinopathysim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_hacks_ndkdemo_MyActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_enability_visionsimulator_diabeticretinopathysim_FindFeatures
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
